### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by casperdcl** [iterative/priority-list#3]
## p1

- [x] put source in separate repo
  + [x] @iterative: migrate slack webhook
  + [x] @iterative: add (fine-grained) github token
  + [x] @iterative: update repos
  + [ ] release on marketplace
- [x] support fine-grained tokens #1
- [x] basic README docs

## p2: inputs

- [x] fix parsing PR `comments` & `reactions` (regression from #2)
- [ ] include PR commit activity (not just comment activity)
  + last updated
  + number of commits
- [ ] increase weight of issues not yet in the GH weekly planning project board?
- [ ] increase weight of issues from external contributors?
- [ ] configurable `label_priority` regexes?
- [ ] exclude weekends/holidays for days stale?
- [ ] increase weight based on time active (`updated - created`)?

## p2: outputs

- [ ] post to some issue comment? https://github.com/iterative/cml/issues/1180
- [ ] post to `gh-pages`?

## p2: @iterative

- [ ] post https://github.com/search?q=label%3Aepic+state%3Aopen+repo%3Aiterative%2Fcml+repo%3Aiterative%2Fcml.dev+... to separate "quarterly roadmap candidates" list?
- [ ] also post a roadmap-specific list
  + labels `epic` & `external-request`
  + just on GH, not slack (or maybe monthly/quarterly on slack?)
